name: barber
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # UI Components and Animations
  cupertino_icons: ^1.0.8                             # iOS Cupertino-style icons
  flutter_svg: ^2.0.10+1                              # Render SVG images
  lottie: ^3.1.2
  hugeicons: ^0.0.7                                   # Huge Icons package
  flutter_spinkit: ^5.1.0                             # Pre-built loading indicators
  #shimmer: ^3.0.0                                    # Shimmer effect for loading states
  flutter_staggered_grid_view: ^0.7.0                 # Staggered grid layout for dynamic UIs
  flutter_staggered_animations: ^1.1.1                # Staggered animations for grid views


  # Routing and Navigation
  go_router: ^14.2.2                                  # Declarative routing management using GoRouter

  # State Management
  flutter_bloc: ^9.0.0                                # BLoC for managing app state
  equatable: ^2.0.5                                   # Simplified equality comparison for model classes
  dartz: ^0.10.1                                      # Functional programming utilities like Either, Option, etc.

  # Dependency Injection & Service Locator
  get_it: ^8.0.3                                    # Service locator for dependency injection

  # Networking and API Calls
  dio: ^5.4.3+1                                     # Powerful HTTP client for handling API requests

  # Local Storage
  hive: ^2.2.3                                      # Lightweight database for Flutter applications

  # Utilities & Enhancements
  url_launcher: ^6.0.20                             # Launch URLs or apps from within the app
  cached_network_image: ^3.2.1                      # Cache and display network images efficiently
  share_plus: ^10.0.2                               # Share content across platforms using native dialogs
  logger: ^2.3.0                                    # Simple and easy-to-use logging package

  # Media Handling
  image_picker: ^1.1.2                              # Pick images/videos from the gallery or camera

  # File Management
  path_provider: ^2.1.4                             # Access the device file system

  # Localization
  easy_localization: ^3.0.7                         # Simplified localization.dart support for multi-language apps





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/svg/
    - assets/translations/


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300